"""Add avatar_url to profiles

Revision ID: 5f17cbc3b506
Revises: a151df10f14c
Create Date: 2026-04-22 08:11:45.915379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f17cbc3b506'
down_revision: Union[str, Sequence[str], None] = 'a151df10f14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avatar_url')
    # ### end Alembic commands ###
